version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 250
  method-lines:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 100
  identical-code:
    config:
      threshold: 100 